"""removed badges from contractor

Revision ID: 164a1f326b12
Revises: 7b2c5765ef9b
Create Date: 2021-11-14 11:07:35.906390-08:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '164a1f326b12'
down_revision = '7b2c5765ef9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contractors', 'badges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractors', sa.Column('badges', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
