"""added new notification settings

Revision ID: 3cb1263a0f82
Revises: fb23308c4e8e
Create Date: 2021-11-18 21:43:30.543322-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb1263a0f82'
down_revision = 'fb23308c4e8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contractors', 'badges')
    op.add_column('notification_settings', sa.Column('accepts_shift', sa.Boolean(), nullable=True))
    op.add_column('notification_settings', sa.Column('begins_shift', sa.Boolean(), nullable=True))
    op.add_column('notification_settings', sa.Column('cancels_shift', sa.Boolean(), nullable=True))
    op.add_column('notification_settings', sa.Column('declines_shift', sa.Boolean(), nullable=True))
    op.add_column('notification_settings', sa.Column('ends_shift', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_settings', 'ends_shift')
    op.drop_column('notification_settings', 'declines_shift')
    op.drop_column('notification_settings', 'cancels_shift')
    op.drop_column('notification_settings', 'begins_shift')
    op.drop_column('notification_settings', 'accepts_shift')
    op.add_column('contractors', sa.Column('badges', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
