"""added certificate_type table

Revision ID: 5729f3847b6b
Revises: cc84cd122b5c
Create Date: 2021-10-15 02:42:51.062017-07:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5729f3847b6b'
down_revision = 'cc84cd122b5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_types_id'), 'certificate_types', ['id'], unique=False)
    op.create_table('shift_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('createdBy', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_request_id'), 'shift_request', ['id'], unique=False)
    op.drop_table('shift_requests')
    op.drop_index('fki_billing_created_by_fkey', table_name='billings')
    op.add_column('certificates', sa.Column('certificate_type_id', sa.Integer(), nullable=True))
    op.alter_column('certificates', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'certificates', 'certificate_types', ['certificate_type_id'], ['id'])
    op.drop_column('certificates', 'name')
    op.alter_column('hotels', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('hotels', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('hotels', 'address')
    op.alter_column('job_roles', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('fki_reviewer', table_name='reviews')
    op.drop_index('fki_shift_cancellations_shift_id_fkey', table_name='shift_cancellations')
    op.drop_index('fki_createdBy', table_name='shifts')
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('fki_createdBy', 'shifts', ['createdBy'], unique=False)
    op.create_index('fki_shift_cancellations_shift_id_fkey', 'shift_cancellations', ['shift_id'], unique=False)
    op.create_index('fki_reviewer', 'reviews', ['reviewer'], unique=False)
    op.alter_column('job_roles', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('hotels', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('hotels', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('hotels', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('certificates', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.alter_column('certificates', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('certificates', 'certificate_type_id')
    op.create_index('fki_billing_created_by_fkey', 'billings', ['createdBy'], unique=False)
    op.create_table('shift_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shift_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdBy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], name='shift_request_created_by_fkey'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name='shift_request_shift_fkey'),
    sa.PrimaryKeyConstraint('id', name='shift_requests_pkey')
    )
    op.drop_index(op.f('ix_shift_request_id'), table_name='shift_request')
    op.drop_table('shift_request')
    op.drop_index(op.f('ix_certificate_types_id'), table_name='certificate_types')
    op.drop_table('certificate_types')
    # ### end Alembic commands ###
