"""added tpe to badges

Revision ID: 7b2c5765ef9b
Revises: b4e3c857c641
Create Date: 2021-11-13 09:21:48.782138-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2c5765ef9b'
down_revision = 'b4e3c857c641'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badges', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badges', 'type')
    # ### end Alembic commands ###
