"""renamed column

Revision ID: bd90c08d2e49
Revises: 5729f3847b6b
Create Date: 2021-10-15 04:16:31.670405-07:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd90c08d2e49'
down_revision = '5729f3847b6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('requiredCertificatesTypes', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('shifts', 'requiredCertificates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('requiredCertificates', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('shifts', 'requiredCertificatesTypes')
    # ### end Alembic commands ###
