"""edited documents table

Revision ID: dd46eeaf10cd
Revises: bd90c08d2e49
Create Date: 2021-10-20 06:19:49.851226-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd46eeaf10cd'
down_revision = 'bd90c08d2e49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'name')
    op.drop_column('documents', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
