"""added address to hotel

Revision ID: e4a442a6942c
Revises: dd46eeaf10cd
Create Date: 2021-10-22 04:04:01.466606-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a442a6942c'
down_revision = 'dd46eeaf10cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'address')
    # ### end Alembic commands ###
