"""added badge_count to contractor

Revision ID: fb23308c4e8e
Revises: 164a1f326b12
Create Date: 2021-11-14 11:12:57.494264-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb23308c4e8e'
down_revision = '164a1f326b12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractors', sa.Column('badge_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contractors', 'badge_count')
    # ### end Alembic commands ###
