CONTRACTOR = "CONTRACTOR"
MANAGER = "MANAGER"
ADMIN = "ADMIN"
PASSWORD_CONFIRM_TYPE = 'PASSWORD_CONFIRM_TYPE'
PASSWORD_CHANGE_TYPE = 'PASSWORD_CHANGE_TYPE'
EMAIL_VERIFICATION_TYPE = 'EMAIL_VERIFICATION_TYPE'
CUSTOMER_IMPORT_TOKEN_TYPE = 'CUSTOMER_IMPORT_TOKEN_TYPE'
EMAIL_LOGIN_TOKEN_TYPE = 'EMAIL_LOGIN_TOKEN_TYPE'
REVIWEE_TYPE_HOTEL = 'HOTEL'
REVIWEE_TYPE_USER = 'USER'
AUDIENCE_TYPE_MARKET = 'MARKET'
AUDIENCE_TYPE_MANUAL = 'MANUAL'
AUDIENCE_TYPE_FAVOURITE = 'FAVOURITE'
NOTIFICATION_BOTH = 'BOTH'
NOTIFICATION_PUSH = 'PUSH'
NOTIFICATION_SELF = 'SELF'
NOTIFICATION_EMAIL = 'EMAIL'
SHIFT_PENDING = 'PENDING'
SHIFT_COMPLETED = 'COMPLETED'
SHIFT_ONGOING = 'ONGOING'
SHIFT_ACCEPTED = 'ACCEPTED'
BILLING_PENDING = 'PENDING'
BILLING_PAID = 'PAID'
ACCEPTED_SHIFT_NOTIFICATION_TITLE = 'Your shift has been accepted'
DECLINE_SHIFT_NOTIFICATION_TITLE = 'Your shift has been declined'
AWARDED_SHIFT_NOTIFICATION_TITLE = 'Your been awarded a Shift'
UPCOMING_SHIFT_NOTIFICATION_TITLE = 'You have an upcoming Shift in 1 hour'
SHIFT_REQUEST_NOTIFICATION_TITLE = 'You have a Shift Request'
SHIFT_COMPLETED_NOTIFICATION_TITLE = 'A Shift has been Completed'
SHIFT_CANCEL = 'SHIFT_CANCEL'
SHIFT_END = 'SHIFT_END'
SHIFT_BEGIN = 'SHIFT_BEGIN'
SHIFT_ACCEPT = 'SHIFT_ACCEPT'
SHIFT_DECLINE = 'SHIFT_DECLINE'

# TODO:
"""
audienceType can be: market, manual, favourite
1:17
market: All contractor will see it
manual: Sending to one single contractor
favourite: sending to your favourite contractor
1:19
while target audience is list of contractors that will see this shift. That is their ID
"""
